---

- hosts: all
  gather_facts: false

  # The variables you would most likely want/need to override have been included
  vars:

    # Facts
    client_agent_status_facts_generate: true
    client_agent_status_facts_verbose: true

    # Reports
    client_agent_status_reports_generate: true
    client_agent_status_reports_backup: false

    reports_details_format: json

  roles:
    - name: oneidentity.authentication_services.client_agent_status
