---

- hosts: all 
  gather_facts: false

  # The variables you would most likely want/need to override have been included
  vars:

    # Active Directory
    client_domain: sample.net
    client_username: user
    client_password: pass

    # Directories
    client_sw_dir: "./files/QAS-4.2.4.25529/client"
    client_sw_tmp_dir: /tmp/1id

    # Facts
    client_preflight_facts_generate: true
    client_preflight_facts_verbose: false

    # Reports
    client_preflight_reports_generate: true
    client_preflight_reports_backup: false 

  roles:
    - name: oneidentity.authentication_services.client_preflight
